In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



In [2]:
#path='/home/juan/Programs/ALF/pyALF/Scripts/ALF_data'
Options=['SpinZ_eqJ','SpinXY_eqJ','SpinT_eqJ','Green_eqJ','Den_eqJ', 'Kinb_eqJ']
RK=['R','K']
for i in [2,5,10]:
    path='../data/my_bonds_2021-05-27-13-12-02/my_bonds_'
    path=path+str(i)+'/'

    filename=path+Options[-1]+RK[0]
    f=open(filename, 'r')

    lines=[]
    for line in f:
        l=[]
        l=[float(i) for i in (line.strip()).split()]
        lines.append(l)
        #print(line,'s')


    ##processing coordinates
    xx=np.array(lines[::2])[:,0]
    yy=np.array(lines[::2])[:,1]
    x=list(set(list(np.array(lines[::2])[:,0])))
    y=list(set(list(np.array(lines[::2])[:,1])))
    x.sort()
    y.sort()
    xpl=[round(i,3) for i in x]
    ypl=[round(i,3) for i in y]

    ## getting values if the correlation functions
    orbsalph=np.array(lines[1::2])[:,0]
    orbsbet=np.array(lines[1::2])[:,1]
    real=np.array(lines[1::2])[:,2]
    realerr=np.array(lines[1::2])[:,3]
    im=np.array(lines[1::2])[:,4]
    imerr=np.array(lines[1::2])[:,5]


    ##plots

    NLx=10
    NLy=1
    Nplx=np.arange(NLx)
    Nply=np.arange(NLy)
    imsq=np.reshape(im,[NLx,NLy])
    #plt.imshow(imsq)
    #plt.xticks(Nplx,xpl)
    #plt.yticks(Nply,ypl)
    #plt.show()

    NLx=10
    NLy=1
    Nplx=np.arange(NLx)
    Nply=np.arange(NLy)
    realsq=np.reshape(real,[NLx,NLy])
    #plt.imshow(realsq)
    #plt.xticks(Nplx,xpl)
    #plt.yticks(Nply,ypl)
    #plt.show()
    NNN=int(NLx/2)-1
    plt.plot(Nplx[NNN:]-NNN,realsq.T[0][NNN:],label=str(i))
    plt.scatter(Nplx[NNN:]-NNN,realsq.T[0][NNN:])
    #plt.plot(Nplx,realsq.T[0],label=str(i))
    #plt.scatter(Nplx,realsq.T[0])
    print(realsq.T[0][6:])
    #plt.xlim([-0.1,14.1])
    #plt.ylim([-0.25,0.25])
plt.legend()
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: '../data/my_bonds_2021-05-27-13-12-02/my_bonds_2/Kinb_eqJR'

In [ ]:
[ 0.00557562 -0.00223807 -0.00042907  0.00311794]
[ 0.02815382 -0.01012779  0.00359352 -0.01019039]
[ 0.04291819 -0.01510879  0.01090308 -0.00755701]


In [ ]:
#path='/home/juan/Programs/ALF/pyALF/Scripts/ALF_data'
Options=['SpinZ_eqJ','SpinXY_eqJ','SpinT_eqJ','Green_eqJ','Den_eqJ', 'Kinb_eqJ']
RK=['R','K']
for i in [2,5,10]:
    path='../data/Stafusa_bonds_2021-05-27-13-09-02/Stafusa_bonds_'
    path=path+str(i)+'/'

    filename=path+Options[-1]+RK[0]
    f=open(filename, 'r')

    lines=[]
    for line in f:
        l=[]
        l=[float(i) for i in (line.strip()).split()]
        lines.append(l)
        #print(line,'s')


    ##processing coordinates
    xx=np.array(lines[::2])[:,0]
    yy=np.array(lines[::2])[:,1]
    x=list(set(list(np.array(lines[::2])[:,0])))
    y=list(set(list(np.array(lines[::2])[:,1])))
    x.sort()
    y.sort()
    xpl=[round(i,3) for i in x]
    ypl=[round(i,3) for i in y]

    ## getting values if the correlation functions
    orbsalph=np.array(lines[1::2])[:,0]
    orbsbet=np.array(lines[1::2])[:,1]
    real=np.array(lines[1::2])[:,2]
    realerr=np.array(lines[1::2])[:,3]
    im=np.array(lines[1::2])[:,4]
    imerr=np.array(lines[1::2])[:,5]


    ##plots

    NLx=10
    NLy=1
    Nplx=np.arange(NLx)
    Nply=np.arange(NLy)
    imsq=np.reshape(im,[NLx,NLy])
    #plt.imshow(imsq)
    #plt.xticks(Nplx,xpl)
    #plt.yticks(Nply,ypl)
    #plt.show()

    NLx=10
    NLy=1
    Nplx=np.arange(NLx)
    Nply=np.arange(NLy)
    realsq=np.reshape(real,[NLx,NLy])
    #plt.imshow(realsq)
    #plt.xticks(Nplx,xpl)
    #plt.yticks(Nply,ypl)
    #plt.show()
    NNN=int(NLx/2)-1
    plt.plot(Nplx[NNN:]-NNN,realsq.T[0][NNN:],label=str(i))
    plt.scatter(Nplx[NNN:]-NNN,realsq.T[0][NNN:])
    #plt.plot(Nplx,realsq.T[0],label=str(i))
    #plt.scatter(Nplx,realsq.T[0])
    print(realsq.T[0][6:])
    #plt.xlim([-0.1,14.1])
    #plt.ylim([-0.25,0.25])
plt.legend()
plt.show()